<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2014/08/01 16:44:21
return array(

  // project
  'baseform' => '/Users/mac_user/Dropbox/projects/htdocs/sf_blog/lib/form/BaseForm.class.php',

  // project_model

  // application
  'myuser' => '/Users/mac_user/Dropbox/projects/htdocs/sf_blog/apps/frontend/lib/myUser.class.php',

  // modules
);
