<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2014/08/01 18:52:59
return array(

  // project
  'addform' => '/Users/mac_user/Dropbox/projects/htdocs/sf_blog/lib/form/AddForm.php',
  'baseform' => '/Users/mac_user/Dropbox/projects/htdocs/sf_blog/lib/form/BaseForm.class.php',
  'editform' => '/Users/mac_user/Dropbox/projects/htdocs/sf_blog/lib/form/EditForm.php',
  'loginform' => '/Users/mac_user/Dropbox/projects/htdocs/sf_blog/lib/form/LoginForm.php',

  // project_model
  'blogmodel' => '/Users/mac_user/Dropbox/projects/htdocs/sf_blog/lib/model/Blog.php',

  // application
  'myuser' => '/Users/mac_user/Dropbox/projects/htdocs/sf_blog/apps/backend/lib/myUser.class.php',

  // modules
);
